### ISSUE TITLE
AceEditorHalogen

### ISSUE THREAD

**Issue by milesfrain** [JordanMartinez/purescript-cookbook#120] opened 2020-07-03 01:19 UTC
```
Unique Recipe Name: AceEditorHalogen
```

**Description of Problem**

Port [Halogen's Ace Editor](https://github.com/purescript-halogen/purescript-halogen/tree/master/examples/ace) example to Halogen Hooks.

There's a partial snippet in https://github.com/thomashoneyman/purescript-halogen-hooks/issues/48

One todo is adding `ace` to the package set.
https://pursuit.purescript.org/packages/purescript-ace/7.0.0

**Comment by JordanMartinez** [comment] 2020-07-03 14:27
Sounds good to me!

**Comment by JordanMartinez** [comment] 2020-07-10 14:20
Closing as this is now a duplicate of #138.

**Comment by JordanMartinez** [comment] 2020-07-15 20:30
I'm reopening this until #162 gets merged.

**Comment by JordanMartinez** [comment] 2020-07-17 01:38
Closed by #162

**Closed by JordanMartinez** 2020-07-17 01:38 UTC
Labels: recipe-request
